#ifndef STATEMENT_HPP
#define STATEMENT_HPP

enum ReadTable{
    READ_SUCCESS,
    FAILED_TO_OPEN_FILE_TABLE,
    FILE_TYPE_NOT_MATCH_TABLE,
    COl_NOT_MATCH,
    ENCODING_NOT_MATCH
};
enum WriteTable{
    WRITE_SUCCESS,
    FAILED_TO_OPEN_FILE_WRITE_TABLE
};
enum ReadDatabase{
    READ_DATABASE_SUCCESS,
    FILE_FORMAT_ERROR_DB,
    FAILED_TO_OPEN_FILE_DB,
};
enum WriteDatabase{
    WRITE_DATABASE_SUCCESS,
    FAILED_TO_OPEN_FILE_DB_OUT,
};
typedef enum {
    PREPARE_SUCCESS,
    PREPARE_SYNTAX_ERROR,
    PREPARE_EMPTY_INUSE,
    PREPARE_UNRECOGNIZED_STATEMENT,
    PREPARE_EXECUTE_ERROR
} PrepareResult;

typedef enum {
    EXECUTE_SUCCESS,
    EXECUTE_FAILED,
} ExecuteResult;

#endif